ARM_HIKEY_OUTSTANDING_PREFETCHERS: "0"
ARM_HIKEY_PREFETCHER_STRIDE: "0"
ARM_HIKEY_PREFETCHER_NPFSTRM: "0"
ARM_HIKEY_PREFETCHER_STBPFDIS: false
ARM_HIKEY_PREFETCHER_STBPFRS: false
PLAT_IMX7: false
ARCH_AARCH32: false
ARCH_AARCH64: false
ARCH_ARM_HYP: false
ARCH_RISCV32: false
ARCH_RISCV64: false
ARCH_X86_64: true # KernelSel4ArchX86_64=ON
ARCH_IA32: false
SEL4_ARCH: "x86_64"
ARCH_X86: true # KernelArchX86=ON
ARCH: "x86"
WORD_SIZE: "64"
PC99_TSC_FREQUENCY: "0"
PLAT_PC99: true # KernelPlatPC99=ON
PLAT_PC99: true # KernelPlatPC99=ON
PLAT: "pc99"
ARM_CORTEX_A7: false
ARM_CORTEX_A8: false
ARM_CORTEX_A9: false
ARM_CORTEX_A15: false
ARM_CORTEX_A35: false
ARM_CORTEX_A53: false
ARM_CORTEX_A55: false
ARM_CORTEX_A57: false
ARM_CORTEX_A72: false
ARCH_ARM_V7A: false
ARCH_ARM_V7VE: false
ARCH_ARM_V8A: false
AARCH64_SERROR_IGNORE: false
KERNEL_MCS: false
ARCH_X86_NEHALEM: false
ARCH_X86_GENERIC: false
ARCH_X86_WESTMERE: false
ARCH_X86_SANDY: false
ARCH_X86_IVY: false
ARCH_X86_HASWELL: false
ARCH_X86_BROADWELL: false
ARCH_X86_SKYLAKE: false
KERNEL_X86_MICRO_ARCH: "nehalem"
ARCH_X86_NEHALEM: true # KernelX86MicroArchNehalem=ON
IRQ_IOAPIC: false
IRQ_PIC: false
KERNEL_IRQ_CONTROLLER: "IOAPIC"
IRQ_IOAPIC: true # KernelIRQControllerIOAPIC=ON
MAX_NUM_IOAPIC: "1"
XAPIC: false
X2APIC: false
KERNEL_LAPIC_MODE: "XAPIC"
XAPIC: true # KernelLAPICModeXPAIC=ON
USE_LOGICAL_IDS: false
CACHE_LN_SZ: "64"
VTX: false
X86_64_VTX_64BIT_GUESTS: false
IOMMU: false
MAX_RMRR_ENTRIES: "1"
MAX_VPIDS: "0"
HUGE_PAGE: true # KernelHugePage=ON
SUPPORT_PCID: false
SYSCALL: false
SYSENTER: false
KERNEL_X86_SYSCALL: "syscall"
SYSCALL: true # KernelX86SyscallSyscall=ON
XSAVE: false
FXSAVE: true # KernelFPUFXSave=ON
KERNEL_X86_FPU: "FXSAVE"
XSAVE_FEATURE_SET: "0"
XSAVE_SIZE: "512"
FSGSBASE_INST: false
FSGSBASE_MSR: true # KernelFSGSBaseMSR=ON
KERNEL_FSGS_BASE: "msr"
MULTIBOOT_GRAPHICS_MODE_NONE: false
MULTIBOOT_GRAPHICS_MODE_TEXT: false
MULTIBOOT_GRAPHICS_MODE_LINEAR: false
KERNEL_MUTLTIBOOT_GFX_MODE: "none"
MULTIBOOT_GRAPHICS_MODE_NONE: true # KernelMultibootGFXModeNone=ON
MULTIBOOT1_HEADER: true # KernelMultiboot1Header=ON
MULTIBOOT2_HEADER: true # KernelMultiboot2Header=ON
KERNEL_SKIM_WINDOW: true # KernelSkimWindow=ON
EXPORT_PMC_USER: false
KERNEL_X86_DANGEROUS_MSR: false
KERNEL_X86_IBRS_NONE: false
KERNEL_X86_IBRS_BASIC: false
KERNEL_X86_IBRS_ALL: false
KERNEL_X86_IBRS: "ibrs_none"
KERNEL_X86_IBRS_NONE: true # KernelX86IBRSnone=ON
KERNEL_X86_IBPB_ON_CONTEXT_SWITCH: false
KERNEL_X86_RSB_ON_CONTEXT_SWITCH: false
HAVE_FPU: true # KernelHaveFPU=ON
PADDR_USER_DEVICE_TOP: "140737488355328"
ROOT_CNODE_SIZE_BITS: "16"
TIMER_TICK_MS: "2"
TIME_SLICE: "5"
RETYPE_FAN_OUT_LIMIT: "256"
MAX_NUM_WORK_UNITS_PER_PREEMPTION: "100"
RESET_CHUNK_BITS: "8"
MAX_NUM_BOOTINFO_UNTYPED_CAPS: "230"
FASTPATH: true # KernelFastpath=ON
EXCEPTION_FASTPATH: false
NUM_DOMAINS: "1"
SIGNAL_FASTPATH: false
NUM_PRIORITIES: "256"
MAX_NUM_NODES: "1"
ENABLE_SMP_SUPPORT: false
KERNEL_STACK_BITS: "12"
FPU_MAX_RESTORES_SINCE_SWITCH: "64"
VERIFICATION_BUILD: false
BINARY_VERIFICATION_BUILD: false
DEBUG_BUILD: true # KernelDebugBuild=ON
HARDWARE_DEBUG_API: false
PRINTING: true # KernelPrinting=ON
KERNEL_INVOCATION_REPORT_ERROR_IPC: false
NO_BENCHMARKS: false
BENCHMARK_GENERIC: false
BENCHMARK_TRACK_KERNEL_ENTRIES: false
BENCHMARK_TRACEPOINTS: false
BENCHMARK_TRACK_UTILISATION: false
KERNEL_BENCHMARK: "none"
NO_BENCHMARKS: true # KernelBenchmarksNone=ON
ENABLE_BENCHMARKS: false
KERNEL_LOG_BUFFER: false
MAX_NUM_TRACE_POINTS: "0"
IRQ_REPORTING: true # KernelIRQReporting=ON
COLOUR_PRINTING: true # KernelColourPrinting=ON
USER_STACK_TRACE_LENGTH: "16"
KERNEL_OPT_LEVEL_O2: false
KERNEL_OPT_LEVEL_OS: false
KERNEL_OPT_LEVEL_O0: false
KERNEL_OPT_LEVEL_O1: false
KERNEL_OPT_LEVEL_O3: false
KERNEL_OPT_LEVEL: "-O2"
KERNEL_OPT_LEVEL_O2: true # KernelOptimisationO2=ON
KERNEL_OPTIMISATION_CLONE_FUNCTIONS: true # KernelOptimisationCloneFunctions=ON
KERNEL_FWHOLE_PROGRAM: false
DANGEROUS_CODE_INJECTION: false
DEBUG_DISABLE_PREFETCHERS: false
SET_TLS_BASE_SELF: true # KernelSetTLSBaseSelf=ON
CLZ_32: false
CLZ_64: false
CTZ_32: false
CTZ_64: false
CLZ_NO_BUILTIN: false
CTZ_NO_BUILTIN: false
