#pragma once

#define CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM1  1
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM2 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM3 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM4 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_TEXT_EGA */
#define CONFIG_LIB_PLAT_SUPPORT_X86_CONSOLE_DEVICE  com1
