LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM1: false
LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM2: false
LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM3: false
LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM4: false
LIB_PLAT_SUPPORT_SERIAL_TEXT_EGA: false
LIB_PLAT_SUPPORT_X86_CONSOLE_DEVICE: "com1"
LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM1: true # LibPlatSupportX86ConsoleDeviceCom1=ON
